# Database Settings
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
## Hibernate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy

# H2 Settings
h2:
  console:
    enabled: true
    path: /h2-console


